h_base_sources = \
	$(top_srcdir)/itpp/base/array.h \
	$(top_srcdir)/itpp/base/bessel.h \
	$(top_srcdir)/itpp/base/binary.h \
	$(top_srcdir)/itpp/base/binfile.h \
	$(top_srcdir)/itpp/base/cblas.h \
	$(top_srcdir)/itpp/base/circular_buffer.h \
	$(top_srcdir)/itpp/base/converters.h \
	$(top_srcdir)/itpp/base/copy_vector.h \
	$(top_srcdir)/itpp/base/elmatfunc.h \
	$(top_srcdir)/itpp/base/errorfunc.h \
	$(top_srcdir)/itpp/base/factory.h \
	$(top_srcdir)/itpp/base/fastmath.h \
	$(top_srcdir)/itpp/base/gf2mat.h \
	$(top_srcdir)/itpp/base/help_functions.h \
	$(top_srcdir)/itpp/base/integration.h \
	$(top_srcdir)/itpp/base/itassert.h \
	$(top_srcdir)/itpp/base/itfile.h \
	$(top_srcdir)/itpp/base/itmisc.h \
	$(top_srcdir)/itpp/base/logexpfunc.h \
	$(top_srcdir)/itpp/base/matfunc.h \
	$(top_srcdir)/itpp/base/mat.h \
	$(top_srcdir)/itpp/base/operators.h \
	$(top_srcdir)/itpp/base/parser.h \
	$(top_srcdir)/itpp/base/random.h \
	$(top_srcdir)/itpp/base/smat.h \
	$(top_srcdir)/itpp/base/sort.h \
	$(top_srcdir)/itpp/base/specmat.h \
	$(top_srcdir)/itpp/base/stack.h \
	$(top_srcdir)/itpp/base/stat.h \
	$(top_srcdir)/itpp/base/svec.h \
	$(top_srcdir)/itpp/base/trihypfunc.h \
	$(top_srcdir)/itpp/base/timing.h \
	$(top_srcdir)/itpp/base/vec.h

cpp_base_sources = \
	$(top_srcdir)/itpp/base/bessel.cpp \
	$(top_srcdir)/itpp/base/binary.cpp \
	$(top_srcdir)/itpp/base/binfile.cpp \
	$(top_srcdir)/itpp/base/cblas.cpp \
	$(top_srcdir)/itpp/base/converters.cpp \
	$(top_srcdir)/itpp/base/elmatfunc.cpp \
	$(top_srcdir)/itpp/base/errorfunc.cpp \
	$(top_srcdir)/itpp/base/fastmath.cpp \
	$(top_srcdir)/itpp/base/gf2mat.cpp \
	$(top_srcdir)/itpp/base/help_functions.cpp \
	$(top_srcdir)/itpp/base/integration.cpp \
	$(top_srcdir)/itpp/base/itassert.cpp \
	$(top_srcdir)/itpp/base/itfile.cpp \
	$(top_srcdir)/itpp/base/itmisc.cpp \
	$(top_srcdir)/itpp/base/mat.cpp \
	$(top_srcdir)/itpp/base/matfunc.cpp \
	$(top_srcdir)/itpp/base/operators.cpp \
	$(top_srcdir)/itpp/base/parser.cpp \
	$(top_srcdir)/itpp/base/random.cpp \
	$(top_srcdir)/itpp/base/smat.cpp \
	$(top_srcdir)/itpp/base/specmat.cpp \
	$(top_srcdir)/itpp/base/stat.cpp \
	$(top_srcdir)/itpp/base/svec.cpp \
	$(top_srcdir)/itpp/base/timing.cpp \
	$(top_srcdir)/itpp/base/vec.cpp
