h_base_sources = \
	$(top_srcdir)/itpp/base/array.h \
	$(top_srcdir)/itpp/base/bessel.h \
	$(top_srcdir)/itpp/base/binary.h \
	$(top_srcdir)/itpp/base/binfile.h \
	$(top_srcdir)/itpp/base/cblas.h \
	$(top_srcdir)/itpp/base/cholesky.h \
	$(top_srcdir)/itpp/base/circular_buffer.h \
	$(top_srcdir)/itpp/base/converters.h \
	$(top_srcdir)/itpp/base/copy_vector.h \
	$(top_srcdir)/itpp/base/det.h \
	$(top_srcdir)/itpp/base/eigen.h \
	$(top_srcdir)/itpp/base/elmatfunc.h \
	$(top_srcdir)/itpp/base/factory.h \
	$(top_srcdir)/itpp/base/fastica.h \
	$(top_srcdir)/itpp/base/fastmath.h \
	$(top_srcdir)/itpp/base/filter.h \
	$(top_srcdir)/itpp/base/filter_design.h \
	$(top_srcdir)/itpp/base/freq_filt.h \
	$(top_srcdir)/itpp/base/gf2mat.h \
	$(top_srcdir)/itpp/base/help_functions.h \
	$(top_srcdir)/itpp/base/integration.h \
	$(top_srcdir)/itpp/base/inv.h \
	$(top_srcdir)/itpp/base/itassert.h \
	$(top_srcdir)/itpp/base/itfile.h \
	$(top_srcdir)/itpp/base/itpp_version.h \
	$(top_srcdir)/itpp/base/lapack.h \
	$(top_srcdir)/itpp/base/ls_solve.h \
	$(top_srcdir)/itpp/base/lu.h \
	$(top_srcdir)/itpp/base/machdep.h \
	$(top_srcdir)/itpp/base/matfunc.h \
	$(top_srcdir)/itpp/base/mat.h \
	$(top_srcdir)/itpp/base/operators.h \
	$(top_srcdir)/itpp/base/newton_search.h \
	$(top_srcdir)/itpp/base/parser.h \
	$(top_srcdir)/itpp/base/poly.h \
	$(top_srcdir)/itpp/base/qr.h \
	$(top_srcdir)/itpp/base/random.h \
	$(top_srcdir)/itpp/base/scalfunc.h \
	$(top_srcdir)/itpp/base/schur.h \
	$(top_srcdir)/itpp/base/sigfun.h \
	$(top_srcdir)/itpp/base/smat.h \
	$(top_srcdir)/itpp/base/sort.h \
	$(top_srcdir)/itpp/base/source.h \
	$(top_srcdir)/itpp/base/specmat.h \
	$(top_srcdir)/itpp/base/stack.h \
	$(top_srcdir)/itpp/base/stat.h \
	$(top_srcdir)/itpp/base/svd.h \
	$(top_srcdir)/itpp/base/svec.h \
	$(top_srcdir)/itpp/base/timing.h \
	$(top_srcdir)/itpp/base/transforms.h \
	$(top_srcdir)/itpp/base/vec.h \
	$(top_srcdir)/itpp/base/window.h

cpp_base_sources = \
	$(top_srcdir)/itpp/base/bessel.cpp \
	$(top_srcdir)/itpp/base/binary.cpp \
	$(top_srcdir)/itpp/base/binfile.cpp \
	$(top_srcdir)/itpp/base/cholesky.cpp \
	$(top_srcdir)/itpp/base/converters.cpp \
	$(top_srcdir)/itpp/base/det.cpp \
	$(top_srcdir)/itpp/base/eigen.cpp \
	$(top_srcdir)/itpp/base/elmatfunc.cpp \
	$(top_srcdir)/itpp/base/fastica.cpp \
	$(top_srcdir)/itpp/base/fastmath.cpp \
	$(top_srcdir)/itpp/base/filter.cpp \
	$(top_srcdir)/itpp/base/filter_design.cpp \
	$(top_srcdir)/itpp/base/freq_filt.cpp \
	$(top_srcdir)/itpp/base/gf2mat.cpp \
	$(top_srcdir)/itpp/base/integration.cpp \
	$(top_srcdir)/itpp/base/inv.cpp \
	$(top_srcdir)/itpp/base/itassert.cpp \
	$(top_srcdir)/itpp/base/itfile.cpp \
	$(top_srcdir)/itpp/base/itpp_version.cpp \
	$(top_srcdir)/itpp/base/ls_solve.cpp \
	$(top_srcdir)/itpp/base/lu.cpp \
	$(top_srcdir)/itpp/base/mat.cpp \
	$(top_srcdir)/itpp/base/matfunc.cpp \
	$(top_srcdir)/itpp/base/operators.cpp \
	$(top_srcdir)/itpp/base/newton_search.cpp \
	$(top_srcdir)/itpp/base/parser.cpp \
	$(top_srcdir)/itpp/base/poly.cpp \
	$(top_srcdir)/itpp/base/qr.cpp \
	$(top_srcdir)/itpp/base/random.cpp \
	$(top_srcdir)/itpp/base/scalfunc.cpp \
	$(top_srcdir)/itpp/base/schur.cpp \
	$(top_srcdir)/itpp/base/sigfun.cpp \
	$(top_srcdir)/itpp/base/smat.cpp \
	$(top_srcdir)/itpp/base/source.cpp \
	$(top_srcdir)/itpp/base/specmat.cpp \
	$(top_srcdir)/itpp/base/stat.cpp \
	$(top_srcdir)/itpp/base/svd.cpp \
	$(top_srcdir)/itpp/base/svec.cpp \
	$(top_srcdir)/itpp/base/timing.cpp \
	$(top_srcdir)/itpp/base/transforms.cpp \
	$(top_srcdir)/itpp/base/vec.cpp \
	$(top_srcdir)/itpp/base/window.cpp
